### ISSUE TITLE
Panic on fuzzer-generated invalid document with DTD

### ISSUE THREAD

**Issue by hanna-kruppe** [RazrFalcon/roxmltree#124]
I pointed `cargo fuzz` at this library for a while, as a sort of "due diligence" before I use it for differential fuzzing of a specialized XML parser I may have to write in the future. The fuzz target that sets `allow_dtd: true` eventually found a crash with this input (after some manual minimization):

```xml
<!DOCTYPE te [
    <!ENTITY d '<p></p></p>'>
]>
<p>&d;&d;
```

When this file is passed to the `ast` example at commit 75f088c979346960038870eca975a62f46b42f1b it panics with the message:

```
thread 'main' panicked at src/parse.rs:821:17:
internal error: entered unreachable code: should be already checked by the tokenizer
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Stack trace with `RUST_BACKTRACE=1`:

<details>

```
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: roxmltree::parse::process_element
             at ./src/parse.rs:821:17
   3: <roxmltree::parse::Context as roxmltree::tokenizer::XmlEvents>::token
             at ./src/parse.rs:655:17
   4: roxmltree::tokenizer::parse_close_element
             at ./src/tokenizer.rs:656:5
   5: roxmltree::tokenizer::parse_content
             at ./src/tokenizer.rs:615:21
   6: roxmltree::parse::process_text
             at ./src/parse.rs:983:17
   7: <roxmltree::parse::Context as roxmltree::tokenizer::XmlEvents>::token
             at ./src/parse.rs:659:17
   8: roxmltree::tokenizer::parse_text
             at ./src/tokenizer.rs:676:5
   9: roxmltree::tokenizer::parse_content
             at ./src/tokenizer.rs:621:22
  10: roxmltree::tokenizer::parse_element
             at ./src/tokenizer.rs:574:9
  11: roxmltree::tokenizer::parse
             at ./src/tokenizer.rs:222:9
  12: roxmltree::parse::parse
             at ./src/parse.rs:600:5
  13: roxmltree::parse::<impl roxmltree::Document>::parse_with_options
             at ./src/parse.rs:395:9
  14: ast::main
             at ./examples/ast.rs:15:11
```

</details>

**Comment by RazrFalcon** [comment]
Yes, DTD is a constant source of problems. Will see how hard to fix this issue.
