### ISSUE TITLE
DOCTYPE causes parsing to fail

### ISSUE THREAD

**Issue by KonradHoeffner** [RazrFalcon/roxmltree#56]
I'm a Rust beginner so maybe I am missing something obvious but when I parse the following string I get an error:

```rust
use roxmltree::Document;
    
const XML: &str = r#"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE szene SYSTEM "szene.dtd">
<szene>
  <triangulation src="abgabetriangulation_high.xml"/>
  <fenster breite="320" hoehe="240"/>
  <raumteilung unterteilung="2"/>
  <kamera>
    <position x="-2.46" y="7.86" z="9.51"/>
    <ziel x="0.03" y="-1.27" z="-2.78"/>
    <fovy winkel="45.0"/>
  </kamera>
  <beleuchtung> 
    <!-- Lichteigenschaften !-->
    <hintergrundfarbe b="0.5" g="0.2" r="0.2"/>
    <ambientehelligkeit b="1" g="1" r="1"/>
    <abschwaechung konstant="1" linear="0" quadratisch="1"/>
    <!-- Lichtquellen !-->
    <lichtquelle>
      <position x="8.07" y="6.48" z="-0.92"/>
      <farbe b="1.0" g="1.0" r="1.0"/>
    </lichtquelle>
    <lichtquelle>
      <position x="-3.00" y="8.35" z="10.65"/>
      <farbe b="1.0" g="1.0" r="1.0"/>
    </lichtquelle>
  </beleuchtung>
</szene>
"#;

fn main()
{
    Document::parse(XML).unwrap();
}
```

```
[...]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParserError(UnknownToken(TextPos { row: 2, col: 1 }))', src/bin/test.rs:36:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.59.0/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/1.59.0/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at /rustc/1.59.0/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/1.59.0/library/core/src/result.rs:1018:23
   4: test::main
             at ./src/bin/test.rs:36:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/1.59.0/library/core/src/ops/function.rs:227:5
```

However when I remove the xml declaration and the doctype it works:

```rust
use roxmltree::Document;
    
    
const XML: &str = r#"
<szene>
  <triangulation src="abgabetriangulation_high.xml"/>
  <fenster breite="320" hoehe="240"/>
  <raumteilung unterteilung="2"/>
  <kamera>
    <position x="-2.46" y="7.86" z="9.51"/>
    <ziel x="0.03" y="-1.27" z="-2.78"/>
    <fovy winkel="45.0"/>
  </kamera>
  <beleuchtung> 
    <!-- Lichteigenschaften !-->
    <hintergrundfarbe b="0.5" g="0.2" r="0.2"/>
    <ambientehelligkeit b="1" g="1" r="1"/>
    <abschwaechung konstant="1" linear="0" quadratisch="1"/>
    <!-- Lichtquellen !-->
    <lichtquelle>
      <position x="8.07" y="6.48" z="-0.92"/>
      <farbe b="1.0" g="1.0" r="1.0"/>
    </lichtquelle>
    <lichtquelle>
      <position x="-3.00" y="8.35" z="10.65"/>
      <farbe b="1.0" g="1.0" r="1.0"/>
    </lichtquelle>
  </beleuchtung>
</szene>
"#;

fn main()
{
    Document::parse(XML).unwrap();
}
```

**Comment by RazrFalcon** [comment]
An XML declaration (`<?xml...`) must start on the first line. In your case it's on the second one.

This is what Python's lxml library would print:

```
lxml.etree.XMLSyntaxError: XML declaration allowed only at the start of the document, line 1, column 7
```

Which is essentially the same as `roxmltree` reports.

You have to write your XML as follows:

```rust
const XML: &str = r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE szene SYSTEM "szene.dtd">
```

no leading whitespaces.

This limitation is by the spec and only for XML declarations. If you don't have it - you can have any amount of whitespaces.

**Comment by KonradHoeffner** [comment]
Ah I didn't think about the newline, thanks for the help!
